repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: Rust format
        description: Format Rust code with rustfmt
        entry: cargo fmt
        language: system
        files: \.rs$
        args: ["--", "--check"]

      - id: clippy
        name: Rust clippy
        description: Run clippy lints on Rust code
        entry: cargo clippy
        language: system
        files: \.rs$
        types: [rust]
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]

  - repo: local
    hooks:
      - id: cargo-test
        name: Cargo test
        description: Run Rust tests
        entry: cargo test
        language: system
        files: \.rs$
        pass_filenames: false

      - id: cargo-check
        name: Cargo check
        description: Check Rust code compiles
        entry: cargo check
        language: system
        files: \.rs$
        pass_filenames: false
